#!/usr/bin/env node
/**
 * Keeps server/README.md in sync with the root README.md.
 *
 * server/README.md is a gitignored build artifact that ships in the npm
 * tarball (package.json `files`). It is regenerated by `npm run build`
 * (server/scripts/copy-assets.mjs), and this script keeps the local copy
 * fresh on every commit via the lefthook pre-commit hook — so the README
 * that npm publishes always matches the repo's README.
 *
 * Run from the repo root:
 *   node scripts/sync-readme.js
 *
 * Exits non-zero if the root README.md is missing.
 */

import { copyFileSync, existsSync, readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const src = join(root, "README.md");
const dst = join(root, "server", "README.md");

if (!existsSync(src)) {
  console.error("  error: root README.md not found — cannot sync server/README.md");
  process.exit(1);
}

if (existsSync(dst) && readFileSync(dst, "utf8") === readFileSync(src, "utf8")) {
  console.log("  server/README.md already in sync with README.md");
} else {
  copyFileSync(src, dst);
  console.log("  server/README.md ← re-synced from README.md");
}